dependencies:
  pre:
    - npm install -g firebase-tools

test:
  override:
    - echo OK

deployment:
  production:
    branch: master
    commands:
      - firebase deploy --token=1/gAGDTRGhfXnN0iyjMlUDpG4wzQa8tYXv6zPnaD-pbGk
