version: 2
# deploy-job:
#        docker:
#          - image: my-image-version-tag
#        working_directory: /tmp/my-project
#        steps:
#          - run:
#              name: Deploy Master to Firebase
#              command: ./node_modules/.bin/firebase deploy --token=1/gAGDTRGhfXnN0iyjMlUDpG4wzQa8tYXv6zPnaD-pbGk
#
#     workflows:
#       version: 2
#
#       -deploy:
#         jobs:
#           - build-job
#           - deploy-job:
#               requires:
#                 - build-job
#               filters:
#                 branches:
#                   only: master

dependencies:
  override:
    - npm install -g firebase-tools
deployment:
  deploy:
    branch: master
    commands:
      - firebase deploy --project "$FIREBASE_PJ" --token "$FIREBASE_TOKEN"

# dependencies:
#   pre:
#     - npm install -g firebase-tools
#
# test:
#   override:
#     - echo OK
#
# deployment:
#   production:
#     branch: master
#     commands:
#       - firebase deploy --token=1/gAGDTRGhfXnN0iyjMlUDpG4wzQa8tYXv6zPnaD-pbGk
