version: 2
jobs:
    build:
        working_directory: ~/portfolio
        machine: true
        steps:
            - run:
                name: install firebase-tools
                command: npm install -g firebase-tools
            - run:
                command: firebase deploy --token "$FIREBASE_TOKEN"
