version: 2
jobs:
    build:
        working_directory: .
        machine: true
        steps:
            - run:
                name: install firebase-tools
                command: npm install -g firebase-tools
            - run:
                command: firebase deploy --project "$FIREBASE_PJ" --token "$FIREBASE_TOKEN"
